version: "3.7"
    
services:
  db:
    image: mysql:5.7
    container_name: db
    volumes:
      - db_data:/var/lib/mysql
      - ./db_backup/dbbackup.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dbname
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: password
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: site
    volumes:
      - wordpress_data:/var/www/html
      - ./site/web/wp-content/:/var/www/html/wp-content/
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: dbuser
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: dbname
      WORDPRESS_DEBUG: 0
volumes:
  db_data: {}
  wordpress_data: {}
